name: Daily Commit

on:
  schedule:
    - cron: '30 5 * * *' # Runs every day at 3 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run Python Script
        run: |
          python daily_commit.py
      - name: Commit Changes
        run: |
          git config --global user.email "syleshrockzz@gmail.com"
          git config --global user.name "sylesh"
          git commit -am "Automated daily commit"
          git push
